### PR TITLE
Update to replace hard coded certs with bosh cli generated certs

### PR DESCRIPTION
**Pull request by calebwashburn**
Also, removed spiff dependency and updated DEVELOP readme.  

Fixes 
- https://github.com/pivotal-cf/pcfdev/issues/293
- https://github.com/pivotal-cf/pcfdev/issues/294
- https://github.com/pivotal-cf/pcfdev/issues/296

### CODE REVIEW

**Comment by sclevine** [comment]
Hi @calebwashburn,

Thanks for the PR! Unfortunately, this code is no longer maintained. We will likely fix the recent certificate expiration by manually modifying the artifact from the previous release. The CI and build infrastructure we used to cut all of the previous releases no longer exists.

We will make the source code for the re-write of PCF Dev (which includes a functional BOSH director and uses native hypervisors!) available soon.

**Comment by sjudeng** [comment]
@calebwashburn Pending a more official solution I tried to build off your branch (thanks for publishing it!). Everything goes well, whereas before it hung starting services yours appears to fully start and I can log in with cf cli. But the apps manager doesn't look like it's deployed (e.g. I get a 404 trying to access). Am I missing something?

```
$ ./bin/build -only=virtualbox-ovf
$ cf dev start -o output/output-virtualbox-ovf/packer-oss-v0.ova
...
Apps Manager URL: https://apps.local.pcfdev.io
...

$ curl -k https://apps.local.pcfdev.io/
404 Not Found: Requested route ('apps.local.pcfdev.io') does not exist.
```

**Comment by calebwashburn** [comment]
This repository appears to be a pure OSS cloudfoundry so none of Pivotal add-ons are present (apps manager, rabbit, scs, etc)

**Comment by sjudeng** [comment]
Ah okay. Thanks for the quick reply.

**Comment by ssisil** [comment]
Fixed in [v0.29](https://github.com/pivotal-cf/pcfdev/releases/tag/v0.29.0)

**Pull request closed without merging**
