### PR TITLE
Fix: linux executed command not producing unique list of cores

### PR DESCRIPTION
**Pull request by lummie**
uniq removes sequentially duplicated lines, therefore input needs sorting first to achieve a unique count. 
Optimum vcpu number in vm should not include hyperthread cpu therefore calculation should be physical cpus \* cores on each cpu 
e.g. I have 2 x 8 core CPUs (hyperthreaded too) old code used to return 32, new calc returns 16.

Fixes : https://github.com/pivotal-cf/pcfdev/issues/55

### CODE REVIEW

**Comment by sclevine** [comment]
Hi @lummie,

Sorry for the delay, and thanks for the PR!

The current implementation filters on `core id`, which should have a unique value for each physical core within a physical CPU, and always be grouped in order (in the case of hyperthreading, they will be next to each other and filtered by `uniq`). For example, two processors with two, dually-hyperthreaded cores each:

```
physical id   0
core id       0
physical id   0
core id       0
physical id   0
core id       1
physical id   0
core id       1

physical id   1
core id       0
physical id   1
core id       0
physical id   1
core id       1
physical id   1
core id       1
```

Would become:

```
core id       0
core id       1
core id       0
core id       1
```

Which `uniq`s to 4 physical cores.

At least, that was the intention. You are correct that some cases (such as two physical CPUs with one core each) don't work with the current logic. However, I worry about two things with your suggestion:
1. Heterogeneous processor environments with different numbers of cores (extremely rare, and not permitted for Intel motherboards)
2. Situations like this: http://askubuntu.com/questions/240235/identical-cores-in-proc-cpuinfo where 8 physical cores would be reported as 4 due to kernel mis-reporting.

That said, I think your implementation is safer for now.

In order for me to merge this PR, you must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA ([individual](https://github.com/pivotal-cf/pcfdev/raw/master/cla/pivotal-icla.pdf) or [corporate](https://github.com/pivotal-cf/pcfdev/raw/master/cla/pivotal-ccla.pdf)).

When sending signed CLA please provide your Github username in case of individual CLA or the list of Github usernames that can make pull requests on behalf of your organization.

Thanks,
Stephen

**Comment by lummie** [comment]
Hi Stephen, I have emailed the CLA.

Just for reference, this is my output... 8 cores on each of 4 CPU

```
$ grep 'core id' /proc/cpuinfo
core id     : 0
core id     : 1
core id     : 2
core id     : 3
core id     : 4
core id     : 5
core id     : 6
core id     : 7
core id     : 0
core id     : 1
core id     : 2
core id     : 3
core id     : 4
core id     : 5
core id     : 6
core id     : 7
core id     : 0
core id     : 1
core id     : 2
core id     : 3
core id     : 4
core id     : 5
core id     : 6
core id     : 7
core id     : 0
core id     : 1
core id     : 2
core id     : 3
core id     : 4
core id     : 5
core id     : 6
core id     : 7
```

Your right about the issues, but as I could not successfully vagrant up (left it all night too) with the old method, it is the lesser of two evils.

I will see if I can improve the detection when I get chance.

Cheers,
Matt

**Comment by sclevine** [comment]
Happy to merge this ASAP! Would you like to rebase your branch to resolve the conflicts first?

**Comment by lummie** [comment]
I think I've done the right thing, first time merging conflicts in a fork :)

**Pull request merged**
