### PR TITLE
Configure PCFDev to user local volume services.

### PR DESCRIPTION
**Pull request by lwoydziak**
As requested by Stephen...

[#132858217](https://www.pivotaltracker.com/story/show/132858217)

Signed-off-by: Luke Woydziak <luke.woydziak@emc.com>

Conflicts:
	versions.json

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lwoydziak Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcfdev&pullRequestId=166)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/pcfdev&pullRequestId=166) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@lwoydziak Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/pcfdev&pullRequestId=166)!

**Comment by lwoydziak** [comment]
We have ran extensive testing on this and have verified correct operation. For reference, we have a CATS like suite called creatively PATS:
https://github.com/cloudfoundry-incubator/persi-acceptance-tests

Inside is an app that will use file persistence ("pora"). The PATS will actually not complete because the configuration of the broker is a little more generic. This is a todo in our backlog regarding PATS configuration.

**Comment by lwoydziak** [comment]
You can run our PATS with the following command:-

```
pushd local-volume-release
./scripts/run-pats admin admin api.local.pcfdev.io local.pcfdev.io local-volume free-local-disk http://local-broker.local.pcfdev.io:8999 admin admin
popd
```

NB: assumes a vanilla environment as it will test registering the local broker

**Comment by aemengo** [comment]
It would be really nice to get a copy of the release tarball when you feel it is ready. We'd like to do the deploy ourselves and see it configured.

**Comment by paulcwarren** [comment]
@aemengo I uploaded all of the releases used to create this here:-
https://s3.amazonaws.com/persi-pcfdev/

HTH

**Comment by lwoydziak** [comment]
Just wanted to follow-up on this. Anything more you need from us to make progress?

**Comment by aemengo** [comment]
No, not at the moment. We have the story prioritized in tracker but we haven't gotten to it yet. Thank you for providing the release .tgz

**Comment by aemengo** [comment]
@lwoydziak Our pipeline makes use of compiled releases for the sake for speed. Any chance that we can get a link to the source code for the local volumes bosh-release?

**Comment by aemengo** [comment]
@lwoydziak Everything looks good. We would like to add this functionality to PCF Dev and routinely build and test the release within our pipeline. However neither the [volume-release-repo](https://github.com/cloudfoundry-incubator/local-volume-release) not the [persi-acceptance-tests](https://github.com/cloudfoundry-incubator/persi-acceptance-tests) have a specified git tag or release to identify as the latest stable build. Is it safe to assume that:

master (621e2377613a9272bb95d332984146f18a5a151a) of the volume-release-repo
(1b7ba49369aedc82685299cfaf139d25971abd73) of the persi-acceptance-tests

would be acceptable points to ship with?

**Comment by lwoydziak** [comment]
The current tip of both repo's master branches are stable:
[caa12f74fe3](https://github.com/cloudfoundry-incubator/persi-acceptance-tests/commit/caa12f74fe379474f53830eb79dd1fb940449e51)
[a9a1a5b52f4e](https://github.com/cloudfoundry-incubator/local-volume-release/commit/a9a1a5b52f4e39009f6fc99620e156e86e296720)

**Comment by sclevine** [comment]
This was merged manually.

**Pull request closed without merging**
